"""
seed.py - Generates the Motif Demo Benchmark Corpus (exactly 300 items).
Includes mocked app reviews, support emails, and one multi-turn enterprise call transcript.
"""

import os
import json
import uuid
import random
import asyncio
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, List

# Output path
SEED_DIR = Path(__file__).resolve().parent / "data" / "seed"
SEED_FILE = SEED_DIR / "corpus_300.json"

# Stable IDs derived from each item's external_id, so re-running this script
# produces an identical corpus file (no spurious git diffs) and identical DB rows.
SEED_NAMESPACE = uuid.UUID("6f1c2a52-8d3e-4b7a-9c1d-2e5f7a9b0c11")


def _stable_id(external_id: str) -> str:
    return str(uuid.uuid5(SEED_NAMESPACE, external_id))


def generate_seed_corpus() -> List[Dict[str, Any]]:
    """
    Generates exactly 300 curated feedback items distributed across:
    - 200 App Store & Public Reviews
    - 80 Customer Support Emails
    - 20 Turns of a Call Transcript (One high-stakes enterprise renewal call)
    """
    random.seed(42)  # Deterministic seed for reproducible benchmarks
    corpus: List[Dict[str, Any]] = []
    base_time = datetime(2026, 9, 1, 9, 0, 0, tzinfo=timezone.utc)

    # Core pain point clusters to distribute realistic themes across sources
    pain_points = [
        {
            "category": "sso_desync",
            "phrase": "Google Workspace SSO tokens expire after 20 minutes and force users to re-login in the middle of active editing sessions.",
            "churn_phrase": "Our IT department has flagged this as an SLA violation. If SSO session persistence isn't resolved by next month we are cancelling our 200-seat contract.",
            "urgency": True,
        },
        {
            "category": "export_truncation",
            "phrase": "Exporting CSV or Excel reports with more than 10,000 rows silently truncates the output file without throwing an error.",
            "churn_phrase": "Our financial audit failed because quarterly revenue reports generated by the tool truncated 4,000 transactions.",
            "urgency": True,
        },
        {
            "category": "mobile_offline_sync",
            "phrase": "The mobile iOS app fails to sync offline changes made during transit, causing conflicting version overwrites when reconnected.",
            "churn_phrase": "Our field engineering agents lost three hours of customer inspection logs today. Considering switching to an alternative solution.",
            "urgency": True,
        },
        {
            "category": "billing_currency_bug",
            "phrase": "Invoices generated in EUR are showing the USD symbol on receipt PDFs, causing compliance headaches with European accounting.",
            "churn_phrase": "Finance team refuses to approve renewal unless VAT invoice currency symbols are rendered accurately.",
            "urgency": False,
        },
        {
            "category": "webhook_retry_storm",
            "phrase": "When endpoint returns 503, Motif initiates an exponential retry storm without jitter, taking down our internal webhook receiver.",
            "churn_phrase": "Your webhook delivery caused a complete outage of our production ingestion server over the weekend.",
            "urgency": True,
        },
        {
            "category": "ui_dark_mode_contrast",
            "phrase": "Dark mode font contrast on secondary table headers is unreadable in bright sunlight.",
            "churn_phrase": "Minor visual annoyance, would be nice to have higher contrast sliders.",
            "urgency": False,
        },
    ]

    enterprise_accounts = [
        {"id": "cust_acme_corp", "tier": "enterprise", "arr": 120000.0, "name": "Acme Global"},
        {"id": "cust_globex_tech", "tier": "enterprise", "arr": 85000.0, "name": "Globex Systems"},
        {"id": "cust_initech_llc", "tier": "enterprise", "arr": 65000.0, "name": "Initech Corp"},
        {"id": "cust_umbrella_bio", "tier": "enterprise", "arr": 140000.0, "name": "Umbrella Corp"},
        {"id": "cust_soylent_ind", "tier": "growth", "arr": 36000.0, "name": "Soylent Tech"},
        {"id": "cust_stark_labs", "tier": "growth", "arr": 24000.0, "name": "Stark Dynamics"},
        {"id": "cust_wayne_sec", "tier": "growth", "arr": 48000.0, "name": "Wayne Enterprises"},
        {"id": "cust_cyberdyne", "tier": "growth", "arr": 18000.0, "name": "Cyberdyne Systems"},
    ]

    # ---------------------------------------------------------
    # 1. 200 Mocked App Store / Public Reviews
    # ---------------------------------------------------------
    for i in range(1, 201):
        point = pain_points[i % len(pain_points)]
        created_at = base_time + timedelta(hours=i * 2, minutes=random.randint(0, 59))
        star_rating = random.choice([1, 2]) if point["urgency"] else random.choice([3, 4])

        # Mix with duplicate candidates for deduplication testing
        # Ground-truth theme label (used only by the P@3 benchmark, never shown to the AI pipeline)
        ground_truth_theme = point["category"]
        if i in [15, 30, 45, 60, 75]:
            # Exact duplicate of preceding item
            content = corpus[i - 2]["content"]
            ground_truth_theme = corpus[i - 2]["metadata"]["ground_truth_theme"]
        elif i in [22, 55, 88, 120]:
            # Near duplicate with minor typo
            content = corpus[i - 2]["content"] + " Please fix this ASAP!"
            ground_truth_theme = corpus[i - 2]["metadata"]["ground_truth_theme"]
        else:
            variations = [
                f"Rating {star_rating}/5: {point['phrase']}",
                f"{point['phrase']} This is creating daily frustration for our team.",
                f"Love the overall vision, but {point['phrase'].lower()} makes it difficult to recommend.",
                f"Frustrating bug: {point['phrase']} Support ticket filed #REV-{1000 + i}.",
            ]
            content = random.choice(variations)

        item = {
            "id": _stable_id(f"appstore_review_{i:04d}"),
            "source_type": "app_store",
            "external_id": f"appstore_review_{i:04d}",
            "content": content,
            "customer_id": f"appstore_user_{100 + (i % 50)}",
            "customer_tier": "starter" if i % 4 == 0 else "free",
            "arr_value": 1200.0 if i % 4 == 0 else 0.0,
            "churn_risk_flag": point["urgency"] and (star_rating <= 2),
            "created_at": created_at.isoformat(),
            "metadata": {
                "rating": star_rating,
                "platform": "ios" if i % 2 == 0 else "android",
                "version": f"2.{i % 5}.0",
                "ground_truth_theme": ground_truth_theme,
            },
        }
        corpus.append(item)

    # ---------------------------------------------------------
    # 2. 80 Sample Customer Support Emails
    # ---------------------------------------------------------
    for j in range(1, 81):
        account = random.choice(enterprise_accounts) if j <= 50 else {
            "id": f"starter_biz_{j}",
            "tier": "starter",
            "arr": 1200.0,
            "name": f"Starter Biz #{j}",
        }
        point = pain_points[j % len(pain_points)]
        created_at = base_time + timedelta(days=j % 20, hours=j % 12, minutes=random.randint(10, 50))

        is_churn = point["urgency"] and (account["tier"] == "enterprise")
        churn_statement = f" {point['churn_phrase']}" if is_churn else ""

        email_body = (
            f"Hi Support Team,\n\n"
            f"We are encountering a critical operational issue with your product: {point['phrase']}{churn_statement}\n\n"
            f"This has impacted our workflows for {random.randint(5, 50)} members of our organization.\n"
            f"Best regards,\n"
            f"{account['name']} IT Administration"
        )

        item = {
            "id": _stable_id(f"email_ticket_{2000 + j}"),
            "source_type": "email",
            "external_id": f"email_ticket_{2000 + j}",
            "content": email_body,
            "customer_id": account["id"],
            "customer_tier": account["tier"],
            "arr_value": account["arr"],
            "churn_risk_flag": is_churn,
            "created_at": created_at.isoformat(),
            "metadata": {
                "subject": f"URGENT: Issue regarding {point['category'].replace('_', ' ').title()}",
                "sender_email": f"it-support@{account['id'].replace('cust_', '')}.com",
                "priority": "P1" if is_churn else "P2",
                "ground_truth_theme": point["category"],
            },
        }
        corpus.append(item)

    # ---------------------------------------------------------
    # 3. 20 Turns of a Call Transcript (One Complete Enterprise Call)
    # ---------------------------------------------------------
    transcript_dialogue = [
        ("CSM", "Good morning Marcus, thank you for joining our Q3 executive account check-in for Acme Global."),
        ("Customer_VP", "Thanks for having me Sarah. I have to be blunt right out of the gate: our team is currently in crisis mode."),
        ("CSM", "I'm sorry to hear that Marcus. Can you walk me through what's happening?"),
        ("Customer_VP", "It's the Google Workspace SSO authentication desync. Our users get forcibly logged out every 20 minutes mid-session."),
        ("CSM", "Understood. Has this been happening across all 200 seats in your enterprise workspace?"),
        ("Customer_VP", "Yes, across all 200 engineering and product seats. It's destroying sprint momentum and wiping out draft pull requests."),
        ("Customer_VP", "Google Workspace SSO tokens expire after 20 minutes and force users to re-login in the middle of active editing sessions."),
        ("CSM", "That is unacceptable. Let me check the ticket logs from our engineering team on that."),
        ("Customer_VP", "I raised this ticket three weeks ago. We haven't had a single concrete timeline or hotfix."),
        ("Customer_VP", "Our IT department has flagged this as an SLA violation. If SSO session persistence isn't resolved by next month we are cancelling our 200-seat contract."),
        ("CSM", "I hear you Marcus. Acme Global is a $120k ARR anchor account for us, and I will personally escalate this to our VP of Engineering today."),
        ("Customer_VP", "I appreciate that Sarah, but we've already initiated conversations with Okta and a competing vendor."),
        ("CSM", "May I ask which specific OAuth flow settings your IT team has enabled in Google Workspace?"),
        ("Customer_VP", "We enforce strict PKCE with hourly token refreshes, but your application server refuses the refresh token and crashes with 401 Unauthorized."),
        ("CSM", "Got it. So it's failing on silent token refresh rather than the initial login."),
        ("Customer_VP", "Exactly. If the user is actively typing, the modal pops up and loses unsaved form state."),
        ("CSM", "I have documented this exact failure mode. I will commit an engineering team to a patch branch by Friday."),
        ("Customer_VP", "If we don't have a verified fix in staging by Friday 5 PM EST, we are withholding our renewal wire."),
        ("CSM", "Understood. I will send you a daily update at 10 AM EST until this is deployed."),
        ("Customer_VP", "Thank you Sarah. We want this partnership to work, but reliability is non-negotiable for enterprise."),
    ]

    call_start_time = datetime(2026, 9, 20, 14, 0, 0, tzinfo=timezone.utc)
    for idx, (speaker, speech) in enumerate(transcript_dialogue):
        turn_time = call_start_time + timedelta(minutes=idx * 2)
        is_churn = "cancelling" in speech.lower() or "withholding" in speech.lower() or "sla violation" in speech.lower()

        item = {
            "id": _stable_id(f"call_transcript_acme_q3_turn_{idx + 1:02d}"),
            "source_type": "transcript",
            "external_id": f"call_transcript_acme_q3_turn_{idx + 1:02d}",
            "content": f"[{speaker}]: {speech}",
            "customer_id": "cust_acme_corp",
            "customer_tier": "enterprise",
            "arr_value": 120000.0,
            "churn_risk_flag": is_churn,
            "created_at": turn_time.isoformat(),
            "metadata": {
                "call_id": "call_acme_q3_renewal_2026",
                "call_title": "Acme Global ($120k ARR) Executive Renewal & Friction Review",
                "speaker": speaker,
                "turn_index": idx + 1,
                "ground_truth_theme": "sso_desync",
            },
        }
        corpus.append(item)

    return corpus


def save_corpus_to_disk(corpus: List[Dict[str, Any]]) -> str:
    """Save the 300 generated items to data/seed/corpus_300.json."""
    SEED_DIR.mkdir(parents=True, exist_ok=True)
    with open(SEED_FILE, "w", encoding="utf-8") as f:
        json.dump(corpus, f, indent=2, ensure_ascii=False)
    return str(SEED_FILE)


async def seed_database_if_available(corpus: List[Dict[str, Any]]) -> bool:
    """Attempt to insert corpus into PostgreSQL database if reachable."""
    try:
        from app.db.session import engine, init_db
        from app.models.feedback import FeedbackItem
        from sqlalchemy.ext.asyncio import AsyncSession
        from sqlalchemy import select, delete

        print("Connecting to database to seed feedback items...")
        await init_db()

        async with AsyncSession(engine) as session:
            # Check existing count
            result = await session.execute(select(FeedbackItem))
            existing = result.scalars().all()
            if existing:
                print(f"Database already contains {len(existing)} feedback items. Replacing with clean 300 benchmark...")
                await session.execute(delete(FeedbackItem))
                await session.commit()

            feedback_objs = [
                FeedbackItem(
                    id=uuid.UUID(item["id"]),
                    source_type=item["source_type"],
                    external_id=item["external_id"],
                    content=item["content"],
                    clean_content=item["content"].strip(),
                    customer_id=item["customer_id"],
                    customer_tier=item["customer_tier"],
                    arr_value=item["arr_value"],
                    churn_risk_flag=item["churn_risk_flag"],
                    metadata_=item["metadata"],
                )
                for item in corpus
            ]

            session.add_all(feedback_objs)
            await session.commit()
            print(f"Successfully seeded {len(feedback_objs)} records into PostgreSQL feedback_items table.")
            return True
    except Exception as e:
        print(f"Database not available for direct seeding ({e}). Seed JSON file is ready for pipeline ingestion.")
        return False


def main():
    print("=" * 60)
    print("MOTIF BENCHMARK CORPUS GENERATOR (PHASE 2)")
    print("=" * 60)

    corpus = generate_seed_corpus()
    total_count = len(corpus)
    app_store_count = sum(1 for x in corpus if x["source_type"] == "app_store")
    email_count = sum(1 for x in corpus if x["source_type"] == "email")
    transcript_count = sum(1 for x in corpus if x["source_type"] == "transcript")
    churn_count = sum(1 for x in corpus if x["churn_risk_flag"])
    total_arr_at_risk = sum(x["arr_value"] for x in corpus if x["churn_risk_flag"])

    print(f"Generated Total Items: {total_count} (Requirement: exactly 300)")
    print(f"  - App Store Reviews : {app_store_count}")
    print(f"  - Support Emails    : {email_count}")
    print(f"  - Call Transcript   : {transcript_count} turns (1 Enterprise Call)")
    print(f"  - Churn Threats     : {churn_count} items")
    print(f"  - ARR at Risk       : ${total_arr_at_risk:,.2f}")

    saved_path = save_corpus_to_disk(corpus)
    print(f"\nCorpus saved to: {saved_path}")

    # Attempt database seed
    asyncio.run(seed_database_if_available(corpus))
    print("=" * 60)


if __name__ == "__main__":
    main()
