import re
from typing import Any, Dict, List, Optional
from app.models.theme import Theme


def generate_mini_prd(
    theme_title: str,
    problem_summary: str,
    revenue_at_risk: float,
    affected_accounts_count: int,
    cited_quotes: List[Dict[str, Any]],
    cluster_id: int,
) -> str:
    """
    Compiles an engineering-ready Mini-PRD with Gherkin acceptance criteria
    and grounded evidence citations (FR-6.1).
    """
    # Format currency
    arr_str = f"${revenue_at_risk:,.2f}"

    # Determine severity label
    if revenue_at_risk >= 100000:
        severity = "CRITICAL (P0 - Enterprise Churn Risk)"
    elif revenue_at_risk >= 25000:
        severity = "HIGH (P1 - Revenue at Stake)"
    else:
        severity = "MEDIUM (P2 - Standard Friction)"

    # Format quotes section
    evidence_lines = []
    if cited_quotes:
        for i, q in enumerate(cited_quotes, 1):
            text = q.get("quote_text", "").strip()
            cid = q.get("customer_id")
            tier = q.get("customer_tier") or "standard"
            arr = float(q.get("arr_value") or 0.0)
            if cid:
                attribution = f"> **Customer:** `{cid}` ({tier.title()}, ARR: ${arr:,.0f})\n"
            else:
                attribution = f"> **Source:** {q.get('source_name') or 'Project document'}\n"
            evidence_lines.append(f"{attribution}> *\"{text}\"*\n")
    else:
        evidence_lines.append("> *No verbatim quotes attached.*")

    evidence_block = "\n".join(evidence_lines)

    # Derive Gherkin criteria from problem summary
    gherkin_scenario = _generate_gherkin_scenario(theme_title, problem_summary)

    prd_markdown = f"""# [PRD] {theme_title}

**Generated by Motif Autonomous Pipeline** | *Theme ID: Cluster #{cluster_id}*

---

## 1. Executive Summary & Impact
* **Revenue at Risk:** **{arr_str}**
* **Affected Accounts Count:** **{affected_accounts_count} Accounts**
* **Prioritization Tier:** `{severity}`
* **Approval Status:** `motif-approved` (Verified by Human PM Gate)

### Customer Problem Statement
{problem_summary}

---

## 2. Grounded User Evidence & Verbatim Citations
*All cited quotes have been verified 100% verbatim against source customer communications.*

{evidence_block}

---

## 3. Technical Considerations & Proposed Scope
* **Root Cause Category:** Ingestion / Session Lifecycle / Edge Handling
* **Performance Impact:** High recurrence across active customer workflows.
* **Security & Reliability:** Critical for enterprise SLA compliance and contractual retention.

### Proposed Architecture Changes:
1. Identify and resolve failure mode in the primary service handling this workflow.
2. Introduce exponential backoff with jitter and automated recovery / session token refresh.
3. Add end-to-end integration tests preventing regressions on high-volume datasets.

---

## 4. Verifiable Acceptance Criteria (Gherkin Format)

```gherkin
{gherkin_scenario}
```

---

## 5. Audit & Compliance Trail
- **Discovered Via:** HDBSCAN Unsupervised Semantic Density Clustering
- **Citation Verification:** Passed 100% deterministic string-matching gate
- **Dispatched to GitHub:** `POST /repos/{{owner}}/{{repo}}/issues`
"""
    return prd_markdown.strip()


def _generate_gherkin_scenario(title: str, summary: str) -> str:
    """Generates standard Given-When-Then acceptance criteria."""
    clean_title = re.sub(r"^Issue:\s*", "", title)
    return f"""Feature: {clean_title}
  As an active user or enterprise customer
  I need reliable operation without unexpected session loss, silent truncation, or errors
  So that our team maintains operational integrity and trust in the platform

  Scenario: Normal workflow execution under standard operating conditions
    Given the user is authenticated in an active workspace session
    When the user triggers the primary workflow or long-running operation
    Then the action should complete successfully with HTTP 200
    And no unsaved form data or state should be lost
    And all audit logs should reflect successful completion

  Scenario: Error handling and graceful recovery
    Given an intermittent upstream timeout or edge condition occurs
    When the system encounters the condition
    Then an informative, non-blocking notification should display to the user
    And the operation should safely retry with jitter without dropping active state
"""
